export const BASKET_ADD_ITEM = 'BASKET_ADD_ITEM'
export const BASKET_REMOVE_ITEM = 'BASKET_REMOVE_ITEM'
export const SAVE_SHIPPING_ADDRESS = 'SAVE_SHIPPING_ADDRESS'
export const SAVE_PAYMENT_METHOD = 'SAVE_PAYMENT_METHOD'