const products = [
    {
        _id: '1',
        name: 'Bedside Table',
        image: '/Images/BedsideTable.webp',
        description: '100% oak, premium finish, readily assembled.',
        brand: 'Ikea',
        category: 'Furniture',
        price: 120.99,
        countInStock: 10,
        rating: 3.7,
        numOfReviews: 8,
    },
    {
        _id: '2',
        name: 'Book Shelf',
        image: '/Images/BookCase.webp',
        description: '100% oak, premium finish, readily assembled.',
        brand: 'Ikea',
        category: 'Furniture',
        price: 340.99,
        countInStock: 10,
        rating: 5,
        numOfReviews: 7,
    },
    {
        _id: '3',
        name: 'King Size Bed',
        image: '/Images/KingSizeBed.webp',
        description: '100% oak, premium finish, readily assembled.',
        brand: 'Ikea',
        category: 'Furniture',
        price: 1250.99,
        countInStock: 10,
        rating: 4.8,
        numOfReviews: 12,
    },
    {
        _id: '4',
        name: 'Dining Table',
        image: '/Images/DiningTable.webp',
        description: 'Table comes with 4 chairs. 100% oak, premium finish, readily assembled.',
        brand: 'Ikea',
        category: 'Furniture',
        price: 749.99,
        countInStock: 10,
        rating: 3.2,
        numOfReviews: 5,
    },
    {
        _id: '5',
        name: 'Accent Chair',
        image: '/Images/Chair.webp',
        description: 'Leather fabric, 100% wood, premium finish, readily assembled.',
        brand: 'Ikea',
        category: 'Furniture',
        price: 374.99,
        countInStock: 10,
        rating: 4.3,
        numOfReviews: 32,
    },
    {
        _id: '6',
        name: 'Wall Art',
        image: '/Images/WallArt.webp',
        description: 'Elegant 2-panel wall art. Each panel measures 120*70 cm.',
        brand: 'Ikea',
        category: 'Decor',
        price: 94.99,
        countInStock: 10,
        rating: 4.4,
        numOfReviews: 5,
    },
    {
        _id: '7',
        name: 'Wall Clock',
        image: '/Images/WallClock.webp',
        description: 'Elegant wall clock measuring 60*60 cm.',
        brand: 'Ikea',
        category: 'Decor',
        price: 45,
        countInStock: 10,
        rating: 4.9,
        numOfReviews: 10,
    },
    {
        _id: '8',
        name: 'Table Lamp',
        image: '/Images/tablelamp.webp',
        description: 'Elegant lamp that could go on your bed side table or study table. 90*30 cm.',
        brand: 'Ikea',
        category: 'Decor',
        price: 79.99,
        countInStock: 10,
        rating: 4.0,
        numOfReviews: 2,
    },
    {
        _id: '9',
        name: 'Wall Mirror',
        image: '/Images/WallMirror.webp',
        description: 'Mirror with a modern design. 90*50 cm.',
        brand: 'Ikea',
        category: 'Decor',
        price: 199.99,
        countInStock: 10,
        rating: 4.7,
        numOfReviews: 16,
    },
    {
        _id: '10',
        name: 'Rug',
        image: '/Images/Rug.webp',
        description: 'Charcoal gray rug. 180*80 cm.',
        brand: 'Ikea',
        category: 'Decor',
        price: 159.99,
        countInStock: 10,
        rating: 3.8,
        numOfReviews: 13,
    },
]

export default products