const products = [
    {
        _id: '501',
        name: 'Bedside Table',
        image: '/Images/BedsideTable.webp',
        description: 'An elegant table that goes on the side of your bed. 100% oak, premium finish, readily assembled.',
        brand: 'Ikea',
        category: 'Furniture',
        price: 430,
        countInStock: 10,
        rating: 3.7,
        numReviews: 8,
    },
    {
        _id: '502',
        name: 'Book Shelf',
        image: '/Images/BookCase.webp',
        description: '100% oak, premium finish, readily assembled.',
        brand: 'Ikea',
        category: 'Furniture',
        price: 650,
        countInStock: 10,
        rating: 4.1,
        numReviews: 7,
    },
    {
        _id: '503',
        name: 'King Size Bed',
        image: '/Images/KingSizeBed.webp',
        description: '100% oak, premium finish, readily assembled.',
        brand: 'Ikea',
        category: 'Furniture',
        price: 1200,
        countInStock: 10,
        rating: 4.8,
        numReviews: 12,
    },
    {
        _id: '504',
        name: 'Dining Table',
        image: '/Images/DiningTable.webp',
        description: 'Table comes with 4 chairs. 100% oak, premium finish, readily assembled.',
        brand: 'Ikea',
        category: 'Furniture',
        price: 950,
        countInStock: 10,
        rating: 3.2,
        numReviews: 5,
    },
    {
        _id: '505',
        name: 'Recliner Chair',
        image: '/Images/ReclinerChair.webp',
        description: 'Leather fabric, 100% wood, premium finish, readily assembled.',
        brand: 'Ikea',
        category: 'Furniture',
        price: 375,
        countInStock: 10,
        rating: 4.3,
        numReviews: 32,
    },
    {
        _id: '506',
        name: 'Wall Art',
        image: '/Images/WallArt.webp',
        description: 'Elegant 2-panel wall art. Each panel measures 120*70 cm.',
        brand: 'Ikea',
        category: 'Decor',
        price: 95,
        countInStock: 10,
        rating: 4.4,
        numReviews: 5,
    },
    {
        _id: '507',
        name: 'Wall Clock',
        image: '/Images/WallClock.webp',
        description: 'Elegant wall clock measuring 60*60 cm.',
        brand: 'Ikea',
        category: 'Decor',
        price: 45,
        countInStock: 10,
        rating: 4.9,
        numReviews: 10,
    },
    {
        _id: '508',
        name: 'Table Lamp',
        image: '/Images/tablelamp.webp',
        description: 'Elegant lamp that could go on your bed side table or study table. 90*30 cm.',
        brand: 'Ikea',
        category: 'Decor',
        price: 78,
        countInStock: 10,
        rating: 4.0,
        numReviews: 2,
    },
    {
        _id: '509',
        name: 'Wall Mirror',
        image: '/Images/WallMirror.webp',
        description: 'Mirror with a modern design. 90*50 cm.',
        brand: 'Ikea',
        category: 'Decor',
        price: 55,
        countInStock: 10,
        rating: 4.7,
        numReviews: 16,
    },
    {
        _id: '510',
        name: 'Rug',
        image: '/Images/Rug.webp',
        description: 'Charcoal gray rug. 180*80 cm.',
        brand: 'Ikea',
        category: 'Decor',
        price: 160,
        countInStock: 10,
        rating: 3.8,
        numReviews: 13,
    },
]

export default products